version: 2
jobs:
  build:
    docker:
      - image: debian:jessie
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, circleci world.
      - run:
          name: Print the Current Time
          command: date
